name: Expo Build

on:
  push:
    branches:
      - main # Change this to the branch you want to trigger the build

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: 🏗 Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: yarn

      - name: 🏗 Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: 'latest'
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install project dependencies
        run: yarn install

      - name: Build Android app
        run: eas build --platform android --local --profile development

      - name: Build iOS app
        run: eas build --platform ios --local --profile development

      - name: Upload Android APK to releases
        uses: actions/upload-artifact@v2
        with:
          name: android
          path: /path/to/android/build/apk # Replace with the actual path to your Android APK

      - name: Upload iOS IPA to releases
        uses: actions/upload-artifact@v2
        with:
          name: ios
          path: /path/to/ios/build/ipa # Replace with the actual path to your iOS IPA
