name: Expo EAS Build & Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Install Expo CLI
        run: npm install expo-cli@latest --global

      - name: Install Dependencies
        run: yarn install

      - name: Build Android APK
        run: expo eas build --platform android --profile production --non-interactive

      - name: Build iOS IPA
        run: expo eas build --platform ios --profile production --non-interactive

      - name: Deploy Web
        run: expo eas build --platform web --profile production --non-interactive

      - name: Upload Android Build
        run: expo eas submit --platform android --profile production --non-interactive

      - name: Upload iOS Build
        run: expo eas submit --platform ios --profile production --non-interactive
